//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchneiderElectric.MindSweeper.Cli {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Ascii {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ascii() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchneiderElectric.MindSweeper.Cli.Ascii", typeof(Ascii).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  _____                        _____
        ///|  __ \                      |  _  |
        ///| |  \/ __ _ _ __ ___   ___  | | | |_   _____ _ __
        ///| | __ / _` | &apos;_ ` _ \ / _ \ | | | \ \ / / _ \ &apos;__|
        ///| |_\ \ (_| | | | | | |  __/ \ \_/ /\ V /  __/ |
        /// \____/\__,_|_| |_| |_|\___|  \___/  \_/ \___|_|
        ///.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___  ____           _   _____                                   
        ///|  \/  (_)         | | /  ___|                                  
        ///| .  . |_ _ __   __| | \ `--.__      _____  ___ _ __   ___ _ __ 
        ///| |\/| | | &apos;_ \ / _` |  `--. \ \ /\ / / _ \/ _ \ &apos;_ \ / _ \ &apos;__|
        ///| |  | | | | | | (_| | /\__/ /\ V  V /  __/  __/ |_) |  __/ |   
        ///\_|  |_/_|_| |_|\__,_| \____/  \_/\_/ \___|\___| .__/ \___|_|   
        ///                                               | |              
        ///                                               |_| [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       __   __            _                _
        ///      \ \ / /           | |              | |
        ///       \ V /___  _   _  | | ___  ___  ___| |
        ///        \ // _ \| | | | | |/ _ \/ __|/ _ \ |
        ///        | | (_) | |_| | | | (_) \__ \  __/_|
        ///        \_/\___/ \__,_| |_|\___/|___/\___(_)
        ///.
        /// </summary>
        internal static string YouLose {
            get {
                return ResourceManager.GetString("YouLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to       __   __                     _       _
        ///      \ \ / /                    (_)     | |
        ///       \ V /___  _   _  __      ___ _ __ | |
        ///        \ // _ \| | | | \ \ /\ / / | &apos;_ \| |
        ///        | | (_) | |_| |  \ V  V /| | | | |_|
        ///        \_/\___/ \__,_|   \_/\_/ |_|_| |_(_)
        ///.
        /// </summary>
        internal static string YouWin {
            get {
                return ResourceManager.GetString("YouWin", resourceCulture);
            }
        }
    }
}
