//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MindSweeper.Cli.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MindSweeper.Cli.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  _   _   ______   _____   _____  ___  ___   _   _ 
        ///| | | |  | ___ \ |  _  | |  _  | |  \/  |  | | | |
        ///| | | |  | |_/ / | | | | | | | | | .  . |  | | | |
        ///| | | |  | ___ \ | | | | | | | | | |\/| |  | | | |
        ///|_| |_|  | |_/ / \ \_/ / \ \_/ / | |  | |  |_| |_|
        ///(_) (_)  \____/   \___/   \___/  \_|  |_/  (_) (_)
        ///.
        /// </summary>
        internal static string Boom {
            get {
                return ResourceManager.GetString("Boom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; can not be more than {1}. The provided value was {2}..
        /// </summary>
        internal static string CommandOptionGreaterThanMaximum {
            get {
                return ResourceManager.GetString("CommandOptionGreaterThanMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; can not be less than {1}. The provided value was {2}..
        /// </summary>
        internal static string CommandOptionLessThanMinimum {
            get {
                return ResourceManager.GetString("CommandOptionLessThanMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately an error occurred..
        /// </summary>
        internal static string CommandResultStatusError {
            get {
                return ResourceManager.GetString("CommandResultStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation issues occurred..
        /// </summary>
        internal static string CommandResultStatusInvalid {
            get {
                return ResourceManager.GetString("CommandResultStatusInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected result: &apos;{0}&apos;..
        /// </summary>
        internal static string CommandResultStatusUnhandled {
            get {
                return ResourceManager.GetString("CommandResultStatusUnhandled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End the current game..
        /// </summary>
        internal static string EndCommandDescription {
            get {
                return ResourceManager.GetString("EndCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully ended your game..
        /// </summary>
        internal static string EndCommandResultStatusAccepted {
            get {
                return ResourceManager.GetString("EndCommandResultStatusAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no game to end!.
        /// </summary>
        internal static string EndCommandResultStatusNotFound {
            get {
                return ResourceManager.GetString("EndCommandResultStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  _____                        _____
        ///|  __ \                      |  _  |
        ///| |  \/ __ _ _ __ ___   ___  | | | |_   _____ _ __
        ///| | __ / _` | &apos;_ ` _ \ / _ \ | | | \ \ / / _ \ &apos;__|
        ///| |_\ \ (_| | | | | | |  __/ \ \_/ /\ V /  __/ |
        /// \____/\__,_|_| |_| |_|\___|  \___/  \_/ \___|_|
        ///.
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Available moves: {0}..
        /// </summary>
        internal static string GameStatusAvailableMoves {
            get {
                return ResourceManager.GetString("GameStatusAvailableMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Bombs: {0}..
        /// </summary>
        internal static string GameStatusBombs {
            get {
                return ResourceManager.GetString("GameStatusBombs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Bombs hit: {0}..
        /// </summary>
        internal static string GameStatusBombsHit {
            get {
                return ResourceManager.GetString("GameStatusBombsHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Columns: {0}..
        /// </summary>
        internal static string GameStatusColumns {
            get {
                return ResourceManager.GetString("GameStatusColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Current square: {0}..
        /// </summary>
        internal static string GameStatusCurrentSquare {
            get {
                return ResourceManager.GetString("GameStatusCurrentSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Remaining lives: {0}..
        /// </summary>
        internal static string GameStatusLives {
            get {
                return ResourceManager.GetString("GameStatusLives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Moves made: {0}..
        /// </summary>
        internal static string GameStatusMoves {
            get {
                return ResourceManager.GetString("GameStatusMoves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Rows: {0}..
        /// </summary>
        internal static string GameStatusRows {
            get {
                return ResourceManager.GetString("GameStatusRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Squares: {0}..
        /// </summary>
        internal static string GameStatusSquares {
            get {
                return ResourceManager.GetString("GameStatusSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___  ____           _   _____                                   
        ///|  \/  (_)         | | /  ___|                                  
        ///| .  . |_ _ __   __| | \ `--.__      _____  ___ _ __   ___ _ __ 
        ///| |\/| | | &apos;_ \ / _` |  `--. \ \ /\ / / _ \/ _ \ &apos;_ \ / _ \ &apos;__|
        ///| |  | | | | | | (_| | /\__/ /\ V  V /  __/  __/ |_) |  __/ |   
        ///\_|  |_/_|_| |_|\__,_| \____/  \_/\_/ \___|\___| .__/ \___|_|   
        ///                                               | |              
        ///                                               |_| [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move to a square..
        /// </summary>
        internal static string MoveCommandDescription {
            get {
                return ResourceManager.GetString("MoveCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving &apos;{0}&apos; from &apos;{1}&apos; to &apos;{2}&apos;....
        /// </summary>
        internal static string MoveCommandDetails {
            get {
                return ResourceManager.GetString("MoveCommandDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooops. You hit a bomb!.
        /// </summary>
        internal static string MoveCommandDidHitBomb {
            get {
                return ResourceManager.GetString("MoveCommandDidHitBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You didn&apos;t hit a bomb. Good skills!.
        /// </summary>
        internal static string MoveCommandDidNotHitBomb {
            get {
                return ResourceManager.GetString("MoveCommandDidNotHitBomb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choices can be either &apos;up&apos;, &apos;down&apos;, &apos;left&apos; or &apos;right&apos; but a successful move is dependent on your current square&apos;s position..
        /// </summary>
        internal static string MoveCommandDirectionArgumentDescription {
            get {
                return ResourceManager.GetString("MoveCommandDirectionArgumentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direction.
        /// </summary>
        internal static string MoveCommandDirectionArgumentHelpName {
            get {
                return ResourceManager.GetString("MoveCommandDirectionArgumentHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current state of play is as follows:.
        /// </summary>
        internal static string MoveCommandResultStatusAccepted {
            get {
                return ResourceManager.GetString("MoveCommandResultStatusAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an active game. Start a new game then make your move..
        /// </summary>
        internal static string MoveCommandResultStatusNotFound {
            get {
                return ResourceManager.GetString("MoveCommandResultStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s not possible to move &apos;{0}&apos; from your current square..
        /// </summary>
        internal static string MoveCommandResultStatusUnprocessable {
            get {
                return ResourceManager.GetString("MoveCommandResultStatusUnprocessable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once started, you will be placed on a square on the very bottom of a playing field that&apos;s similar to a chess board.
        ///
        ///To compete you must issue simple CLI commands to move one square at a time in a direction of your choosing.
        ///
        ///Each move requires a great deal of consideration because the destination square may or may not have been randomly allocated an explosive device.
        ///
        ///Stepping on such as square will kill you!
        ///
        ///To win, you must make it to the top without losing all your lives.
        ///
        ///Good luck!!.
        /// </summary>
        internal static string RootCommandDescription {
            get {
                return ResourceManager.GetString("RootCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of bombs..
        /// </summary>
        internal static string StartCommandBombsOptionDescription {
            get {
                return ResourceManager.GetString("StartCommandBombsOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bombs.
        /// </summary>
        internal static string StartCommandBombsOptionHelpName {
            get {
                return ResourceManager.GetString("StartCommandBombsOptionHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of columns..
        /// </summary>
        internal static string StartCommandColumnsOptionDescription {
            get {
                return ResourceManager.GetString("StartCommandColumnsOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to columns.
        /// </summary>
        internal static string StartCommandColumnsOptionHelpName {
            get {
                return ResourceManager.GetString("StartCommandColumnsOptionHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new game..
        /// </summary>
        internal static string StartCommandDescription {
            get {
                return ResourceManager.GetString("StartCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of lives..
        /// </summary>
        internal static string StartCommandLivesOptionDescription {
            get {
                return ResourceManager.GetString("StartCommandLivesOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lives.
        /// </summary>
        internal static string StartCommandLivesOptionHelpName {
            get {
                return ResourceManager.GetString("StartCommandLivesOptionHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully started a new game. The current state of play is as follows:.
        /// </summary>
        internal static string StartCommandResultStatusAccepted {
            get {
                return ResourceManager.GetString("StartCommandResultStatusAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have an active game. Please end the current game before starting a new one..
        /// </summary>
        internal static string StartCommandResultStatusConflict {
            get {
                return ResourceManager.GetString("StartCommandResultStatusConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of rows..
        /// </summary>
        internal static string StartCommandRowsOptionDescription {
            get {
                return ResourceManager.GetString("StartCommandRowsOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rows.
        /// </summary>
        internal static string StartCommandRowsOptionHelpName {
            get {
                return ResourceManager.GetString("StartCommandRowsOptionHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the status of your current game..
        /// </summary>
        internal static string StatusCommandDescription {
            get {
                return ResourceManager.GetString("StatusCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have an active game. Start a new game to play..
        /// </summary>
        internal static string StatusCommandResultStatusNotFound {
            get {
                return ResourceManager.GetString("StatusCommandResultStatusNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an active game. The current state of play is as follows:.
        /// </summary>
        internal static string StatusCommandResultStatusOk {
            get {
                return ResourceManager.GetString("StatusCommandResultStatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __   __  _____   _____   _   _ 
        ///\ \ / / |  ___| /  ___| | | | |
        /// \ V /  | |__   \ `--.  | | | |
        ///  \ /   |  __|   `--. \ | | | |
        ///  | |   | |___  /\__/ / |_| |_|
        ///  \_/   \____/  \____/  (_) (_)
        ///.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     __   __            _                _
        ///    \ \ / /           | |              | |
        ///     \ V /___  _   _  | | ___  ___  ___| |
        ///      \ // _ \| | | | | |/ _ \/ __|/ _ \ |
        ///      | | (_) | |_| | | | (_) \__ \  __/_|
        ///      \_/\___/ \__,_| |_|\___/|___/\___(_)
        ///.
        /// </summary>
        internal static string YouLose {
            get {
                return ResourceManager.GetString("YouLose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     __   __                     _       _
        ///    \ \ / /                    (_)     | |
        ///     \ V /___  _   _  __      ___ _ __ | |
        ///      \ // _ \| | | | \ \ /\ / / | &apos;_ \| |
        ///      | | (_) | |_| |  \ V  V /| | | | |_|
        ///      \_/\___/ \__,_|   \_/\_/ |_|_| |_(_)
        ///.
        /// </summary>
        internal static string YouWin {
            get {
                return ResourceManager.GetString("YouWin", resourceCulture);
            }
        }
    }
}
